apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
spec:
  type: NodePort
  selector:
    app: lab-nginx # Seleciona Pods com label app: nginx-app
  ports:
    - port: 80 # Porta que o Service expõe internamente
      targetPort: 80 # Porta na qual o container Nginx está escutando
      nodePort: 30000 # Porta que será aberta em CADA Node para acesso externo
